name: main pipeline

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  
  short:
    runs-on: ubuntu-latest
    outputs:
      SHORT_SHA: ${{ steps.short-sha.outputs.SHORT_SHA }}
    steps:
      - name: short sha
        id: short-sha
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  build-test:
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      node_version: 20
      run_tests: true

  docker:
    needs: [build-test, short]
    uses: ./.github/workflows/reusable-docker.yml
    with:
      image_name: "my-app"
      tags: '["latest", "sha-${{ needs.short.outputs.SHORT_SHA }}"]'
    secrets:
      DOCKER_USERNAME: ${{ vars.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

  scan:
    needs: [docker, short]
    runs-on: ubuntu-latest
    steps:
      - name: Scan Docker Image for Vulnerabilities
        uses: aquasecurity/trivy-action@0.35.0
        with:
          image-ref: '${{ vars.DOCKER_USERNAME }}/my-app:sha-${{ needs.short.outputs.SHORT_SHA }}'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db,aquasecurity/trivy-db # Use a backup DB if rate-limited
          TRIVY_NO_PROGRESS: "true"
          TRIVY_CACHE_DIR: .trivycache # Force a fresh directory
      - name: sarif output
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ vars.DOCKER_USERNAME }}/my-app:sha-${{ needs.short.outputs.SHORT_SHA }}'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - name: upload sarif
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
  deploy:
    needs: [docker, scan]
    runs-on: ubuntu-latest
    environment: production
    steps:
      
      - name: print
        run: |
          echo "Deploying image: ${{ needs.docker.outputs.image_url }} to production"
   