name: reusable docker

on:
  workflow_call:

    inputs:

      image_name: 
        type: string
        required: true

      tags:
        type: string
        required: false
        
    outputs:
      
      image_url:
        value: ${{ jobs.build.outputs.url }}

    secrets:
     
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:

  build:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.set-url.outputs.url}}
    strategy:
      matrix:
        tag: ${{ fromJSON(inputs.tags) }} # This converts the string back into a list
    steps:

      - name: checkout
        uses: actions/checkout@v5

      - name: login to doker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: build and push
        uses: docker/build-push-action@v5
        id: get-url
        with:
          context: .
          no-cache: true
          push: true
          tags: |-
            ${{ secrets.DOCKER_USERNAME }}/${{ inputs.image_name }}:${{ matrix.tag }}

      - name: output
        id: set-url
        run: echo "url=${{ inputs.image_name }}:${{ matrix.tag }}" >> "$GITHUB_OUTPUT"
