name: smart pipeline
on:
  #push:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install eslint + parser
        run: npm install --save-dev eslint@9 @eslint/js@9 @babel/eslint-parser @babel/preset-react --legacy-peer-deps

      - name: install dependencies
        run: npm ci

      - name: run lint
        run: npm run lint -- --ignore-pattern "**/*.test.jsx"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: npm

      - name: install dependencies
        run: npm ci

      - name: run test
        run: npm test

  summary:
    needs: 
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - name: Print pushed branch name
        run: echo "Branch Name :" ${{ github.ref_name }}
      - name: Print commit message
        run: echo "Commit message :" ${{ github.event.head_commit.message }}
